#!/usr/bin/env bash

CONF=

PRJ=
ID=
BASE=
CMD=

while getopts "B:p:i:s" opt; do
    case "${opt}" in
        B)
            BASE="$OPTARG"
            ;;
        p)
            PRJ="$OPTARG"
            ;;
        i)
            ID="$OPTARG"
            ;;
        *)
            echo "error: invalid option"
            exit 1
            ;;
    esac
done

shift $((OPTIND-1))
CMD="$1"


# Dumb wrapper so a plugin can call its libraries
[ -z "$CMD" ] && CMD="sync"
CWD="$(pwd)"
PGNDIR="`dirname $0`"

cd "$PGNDIR" || exit 1
lua gun.lua -p "$PRJ" -B "$BASE" -i "$ID" "$CMD"
cd "$CWD" || exit 1
