#include <stdio.h>
#include <time.h>
#include <string.h>

#include "cli.h"
#include "aux/config.h"
#include "aux/toggle.h"

// TODO: load current project/board

/* Note: should be static cuz args->task point to it.  */
static char gentask[IDSIZ + 1];

static int generate_task(tman_arg_t * args)
{
    args->task = gentask;
    for (register unsigned int i = 1; i < IDLIMIT; ++i) {
        sprintf(gentask, IDFMT, i);
        if (tman_check_arg_task_exist(args) != LIBTMAN_OK)
            return 0;
    }
    return 1;
}

static int generate_units(tman_ctx_t * ctx, char *prj, char *task)
{
    char date[BUFSIZ + 1];
    struct tman_unit *units = NULL;
    time_t rawtime = time(NULL);
    const char timefmt[] = "%Y%m%d";
    struct tm *timeinfo = localtime(&rawtime);
    char desc[100] = "autogenerated desciption for ";
    char *unitvals[] = { "mid", "task", date, desc, };

    strcat(desc, task);
    strftime(date, BUFSIZ, timefmt, timeinfo);

    for (int i = 0; i < nunitkey; ++i)
        units = tman_unit_add(units, unitkeys[i], unitvals[i]);
    ctx->units = units;
    return 0;
}

int tman_cli_add(int argc, char **argv, tman_ctx_t * ctx)
{
    char *errfmt;
    tman_arg_t args;
    char *last_task;
    int quiet, showhelp, status, switch_dir, switch_task, i, c;

    last_task = NULL;
    quiet = showhelp = FALSE;
    switch_dir = switch_task = TRUE;
    args.prj = args.brd = args.task = NULL;
    errfmt = "cannot create task '%s': %s";
    while ((c = getopt(argc, argv, ":b:np:hqN")) != -1) {
        switch (c) {
        case 'b':
            args.brd = optarg;
            break;
        case 'p':
            args.prj = optarg;
            break;
        case 'h':
            showhelp = TRUE;
            break;
        case 'n':
            switch_task = FALSE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case 'N':
            switch_dir = FALSE;
            switch_task = FALSE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp == TRUE)
        return help_usage("add");

    if ((status = toggle_prj_get_curr(tmancfg->base.task, &args))) {
        if (quiet == FALSE)
            elog(status, errfmt, "NOCURR", "no current project");
        return status;
    } else if ((status = toggle_brd_get_curr(tmancfg->base.task, &args))) {
        if (quiet == FALSE)
            elog(status, errfmt, "NOCURR", "no current board");
        return status;
    } else if (optind == argc && generate_task(&args)) {
        if (quiet == FALSE)
            elog(1, "could not generate task ID: limit is %d", IDLIMIT);
        return 1;
    } else if ((ctx->column = generate_column("todo")) == NULL) {
        if (quiet == FALSE)
            elog(1, "could not generate column");
        return 1;
    }

    i = optind;
    do {
        // TODO: maybe there's no need cuz i use task ID generator
        args.task = args.task == NULL ? argv[i] : args.task;

        if (generate_units(ctx, args.prj, args.task)) {
            if (quiet == FALSE)
                elog(1, errfmt, args.task, "unit generation failed");
            continue;
        } else if ((status = tman_task_add(ctx, &args)) != LIBTMAN_OK) {
            if (quiet == FALSE)
                elog(status, errfmt, args.task, tman_strerror());
        } else if (hook_action(&args, "add")) {
            if (quiet == FALSE)
                elog(1, errfmt, args.task, "failed to execute hooks");
        }

        ctx->units = tman_unit_free(ctx->units);

        /* TODO: find a better trick.  */
        last_task = args.task;
        args.task = NULL;       /* unset task ID, not to break loop.  */
    } while (++i < argc);

    args.task = last_task;

    if ((switch_task && status == LIBTMAN_OK)
        && toggle_task_set_curr(tmancfg->base.task, &args)) {
        if (quiet == FALSE)
            elog(status, "could not update toggles");
        return 1;
    }

    return (switch_dir && status == LIBTMAN_OK) ? tman_pwd_task(&args) : status;
}
