#include <ctype.h>
#include <string.h>
#include <dirent.h>

#include "cli.h"
#include "aux/toggle.h"
#include "aux/config.h"

static int valid_desc(const char *val)
{
    if (!isalnum(*val++))
        return FALSE;
    for (; *val; ++val)
        if (!(isalnum(*val) || isspace(*val) || *val == '_' || *val == '-'))
            return FALSE;
    return isalnum(*--val) != 0;
}

static int generate_units(tman_ctx_t * ctx, char *brd)
{
    struct tman_unit *units = NULL;
    char desc[100] = "autogenerated desciption for board ";

    strcat(desc, brd);
    units = tman_unit_add(units, "desc", desc);
    ctx->units = units;
    return 0;
}

// TODO: add support to generate board name
static int _board_add(int argc, char **argv, tman_ctx_t * ctx)
{
    char c;
    tman_arg_t args;
    const char *errfmt = "cannot add board '%s': %s";
    int i, quiet, showhelp, status;

    status = LIBTMAN_OK;
    showhelp = quiet = FALSE;
    args.prj = args.brd = args.task = NULL;
    while ((c = getopt(argc, argv, ":hnp:q")) != -1) {
        switch (c) {
        case 'h':
            showhelp = TRUE;
            break;
        case 'n':
            //opt.brd_switch = FALSE;
            break;
        case 'p':
            args.prj = optarg;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("brd-add");

    if (optind == argc)
        return elog(1, "board name required");
    else if ((ctx->column = generate_column("todo")) == NULL) {
        if (quiet == FALSE)
            elog(1, "could not generate column");
        return 1;
    }

    if ((status = toggle_prj_get_curr(tmancfg->base.task, &args))) {
        return status;
    }

    for (i = optind; i < argc; ++i) {
        args.brd = argv[i];

        elog(1, "cli_brd:start prj '%s'", args.prj);
        if (generate_units(ctx, args.brd)) {
            if (quiet == FALSE)
                elog(1, errfmt, args.prj, "unit generation failed");
            continue;
        }
        if ((status = tman_brd_add(ctx, &args)) != LIBTMAN_OK) {
            if (quiet == FALSE)
                elog(1, errfmt, argv[i], tman_strerror());
            ctx->units = tman_unit_free(ctx->units);
            continue;
        }
        // TODO: add hooks
        ctx->units = tman_unit_free(ctx->units);
        elog(1, "cli_brd:done prj '%s'", args.prj);
    }

    ctx->column = tman_unit_free(ctx->column);
    //return status == LIBTMAN_OK ? tman_pwd_board() : 1;
    return 0;
}

static int _board_del(int argc, char **argv, tman_ctx_t * ctx)
{
    char c;
    tman_arg_t args;
    const char *errfmt = "cannot delete: %s";
    int i, choice, quiet, showhelp, showprompt, status;

    showprompt = TRUE;
    status = LIBTMAN_OK;
    choice = quiet = showhelp = FALSE;
    args.prj = args.brd = args.task = NULL;
    while ((c = getopt(argc, argv, ":hnq")) != -1) {
        switch (c) {
        case 'h':
            showhelp = TRUE;
            break;
        case 'n':
            showprompt = FALSE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("brd-del");

    i = optind;
    do {
        args.brd = argv[i];

        if (showprompt) {
            /* TODO: show board name.  */
            printf("Are you sure to delete board(s)? [y/N] ");
            if ((choice = getchar()) != 'y' && choice != 'Y')
                continue;
        }

        if ((status = tman_brd_del(ctx, &args)) != LIBTMAN_OK) {
            if (quiet == FALSE)
                elog(status, errfmt, argv[i], tman_strerror());
        }
    } while (++i < argc);

    // TODO: update current directory if current prj got deleted.
    return status == LIBTMAN_OK ? tman_pwd_board() : status;
}

static int _board_export(int argc, char **argv, tman_ctx_t * ctx)
{
    return elog(1, "%s: under development", __FUNCTION__);
}

static int _board_import(int argc, char **argv, tman_ctx_t * ctx)
{
    return elog(1, "%s: under development", __FUNCTION__);
}

static int _board_list(int argc, char **argv, tman_ctx_t * ctx)
{
    tman_arg_t args;
    int c, i, quiet, status;
    const char *errfmt = "cannot list board(s) '%s': %s";

    quiet = FALSE;
    while ((c = getopt(argc, argv, ":q")) != -1) {
        switch (c) {
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    i = optind;
    do {
        args.prj = argv[i];
        if ((status = tman_brd_list(ctx, &args)) != LIBTMAN_OK) {
            args.prj = args.prj ? args.prj : "NOCURR";
            if (quiet == FALSE)
                elog(status, errfmt, args.prj, tman_strerror());
            continue;
        }
    } while (++i < argc);
    return status;
}

static int _board_prev(int argc, char **argv, tman_ctx_t * ctx)
{
    return elog(1, "under development");
}

static int _board_move(int argc, char **argv, tman_ctx_t * ctx)
{
    return elog(1, "%s: under development", __FUNCTION__);
}

static int _board_set(int argc, char **argv, tman_ctx_t * ctx)
{
    tman_arg_t args;
    int atleast_one_key_set;
    int c, i, quiet, showhelp;
    const char *errfmt = "could not set board unit value '%s': %s";

    quiet = showhelp = FALSE;
    atleast_one_key_set = FALSE;
    args.prj = args.brd = args.task = NULL;
    while ((c = getopt(argc, argv, ":d:hq")) != -1) {
        switch (c) {
        case 'd':
            if (valid_desc(optarg) == FALSE) {
                elog(1, "invalid description '%s'", optarg);
                help_usage("brd-set");
                return 1;
            }
            atleast_one_key_set = TRUE;
            ctx->units = tman_unit_add(ctx->units, "desc", optarg);
            break;
        case 'h':
            showhelp = TRUE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("brd-set");
    if (atleast_one_key_set == FALSE) {
        elog(1, "gotta supply one of the options");
        help_usage("brd-set");
        return 1;
    }

    i = optind;
    do {
        int status;
        args.brd = argv[i];

        if ((status = tman_brd_set(ctx, &args)) != LIBTMAN_OK) {
            if (quiet == FALSE)
                elog(status, errfmt, argv[i], tman_strerror());
        }
    } while (++i < argc);

    ctx->units = tman_unit_free(ctx->units);
    return 0;
}

static int _board_show(int argc, char **argv, tman_ctx_t * ctx)
{
    tman_arg_t args;
    int c, i, quiet, showhelp, status;
    struct tman_unit *units, *unitpgn;
    const char *errfmt = "cannot show project units '%s': %s";

    units = unitpgn = NULL;
    quiet = showhelp = FALSE;
    args.prj = args.brd = args.task = NULL;
    while ((c = getopt(argc, argv, ":hq")) != -1) {
        switch (c) {
        case 'h':
            showhelp = TRUE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("brd-show");

    i = optind;
    do {
        args.brd = argv[i];
        if ((status = tman_brd_get(ctx, &args)) != LIBTMAN_OK) {
            if (quiet == FALSE)
                elog(status, errfmt, argv[i], tman_strerror());
            continue;
        }

        printf("%-7s : %s\n", "brd", args.brd);
        for (units = ctx->units; units; units = units->next)
            printf("%-7s : %s\n", units->key, units->val);

        // TODO: add plugin output
    } while (++i < argc);

    return status;
}

static int _board_sync(int argc, char **argv, tman_ctx_t * ctx)
{
    tman_arg_t args;
    int c, i, quiet, showhelp, status;
    const char *errfmt = "cannot switch to '%s': %s";

    quiet = showhelp = FALSE;
    args.prj = args.brd = args.task = NULL;
    while ((c = getopt(argc, argv, ":hnp:q")) != -1) {
        switch (c) {
        case 'h':
            showhelp = TRUE;
            break;
        case 'n':
            //opt.brd_switch = FALSE;
            break;
        case 'p':
            args.prj = optarg;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("brd-sync");

    i = optind;
    do {
        args.brd = argv[i];
        if ((status = tman_brd_sync(ctx, &args)) != LIBTMAN_OK) {
            if (quiet == FALSE)
                elog(status, errfmt, argv[i], tman_strerror());
        }
    } while (++i < argc);

    //return opt.brd_switch && status == LIBTMAN_OK ? tman_pwd_board() : status;
    return status == LIBTMAN_OK ? tman_pwd_board() : status;
}

static const builtin_t brdcmds[] = {
    {.name = "add",.func = &_board_add},
    {.name = "del",.func = &_board_del},
    {.name = "export",.func = &_board_export},  /* export tasks into board */
    {.name = "import",.func = &_board_import},  /* import tasks from board */
    {.name = "list",.func = &_board_list},
    {.name = "prev",.func = &_board_prev},
    {.name = "move",.func = &_board_move},
    {.name = "set",.func = &_board_set},
    {.name = "show",.func = &_board_show},
    {.name = "sync",.func = &_board_sync},
};

int tman_cli_board(int argc, char **argv, tman_ctx_t * ctx)
{
    char *cmd;

    if ((cmd = argv[1]) == NULL)
        return elog(1, "brd command is missing");

    for (int i = 0; i < ARRAY_SIZE(brdcmds); ++i)
        if (strncmp(cmd, brdcmds[i].name, CMDSIZ) == 0)
            return brdcmds[i].func(argc - 1, argv + 1, ctx);

    return elog(1, "'%s': no such brd subcommand", cmd);
}
