#include <stdio.h>
#include <string.h>

#include "tec.h"

#define PADDING     "    "
#define SYSTEM      "system"
#define TAGOBJ      "bin-object"
#define TAGOBJCMD   "bin-object-cmd"
#define TAGSYSTEM   "bin-system"
#define TAGBASIC    "bin-basic"

struct help {
    const char *tag;
    const char *name;
    const char *synop;
    const char *desc_short;
    const char *desc_long;
};

struct helpctx {
    int synop;
    int desc_short;
    int desc_long;
};

struct helpctx helpctx = {
    .synop = false,
    .desc_short = false,
    .desc_long = false,
};

struct help helptab[] = {
    {
     .tag = SYSTEM,
     .name = "tec",
     .synop = "Usage: " PROGRAM " [OPTION]... COMMAND|PLUGIN\n",
     .desc_short = "Terminal project and task manager.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -v      show version and exit\n\
      -C TOG  enbale colors (default: disabled)\n\
      -D TOG  enbale debug mode (default: disabled)\n\
      -F DIR  path to the config file (under development)\n\
      -H TOG  enbale hooks (default: disabled)\n\
      -P DIR  directory where plugins are stored\n\
      -T DIR  directory where tasks are stored\n\
    \n\
    Arguments:\n\
      DIR     path to directory\n\
      TOG     can be either 'on' or 'off'\n\
    \n\
    Notes:\n\
    It's more convient to set options in config file. This way no need\n\
    to type them every time.\n\
    \n\
    Exit status:\n\
    Return status of builtin command or plugin\n"},
    {
     .tag = TAGSYSTEM,
     .name = "help",
     .synop = "Usage: " PROGRAM " help [OPTION] [CMD]\n",
     .desc_short = "Show help for commands.\n",
     .desc_long = "\n\
    If no CMD passed, list all commands with short description.\n\
    \n\
    Options:\n\
      -d      output short description for each topic\n\
      -s      output only a short usage synopsis for each topic matching\n\
    \n\
    Arguments:\n\
      CMD     builtin command\n\
    \n\
    Exit status:\n\
    Returns success unless PATTERN is not found or an invalid option is given.\n"},
    {
     .tag = TAGSYSTEM,
     .name = "init",
     .synop = "Usage: " PROGRAM " init\n",
     .desc_short = "Init directory structure.\n",
     .desc_long = "\n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGSYSTEM,
     .name = "version",
     .synop = "Usage: " PROGRAM " version\n",
     .desc_short = "Show program version.\n",
     .desc_long = "\n\
    Exit status:\n\
    Under development\n"},

    {
     .tag = TAGBASIC,
     .name = "add",
     .synop = "Usage: " PROGRAM " add [OPTION]... [ID]...\n",
     .desc_short = "Add a new task to project.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name (default is current)\n\
      -h      show this help and exit\n\
      -n      do not switch to task\n\
      -p PRJ  project name (default is current)\n\
      -q      do not write anything to standard error output\n\
      -N      neither switch to task nor to task directory\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      ID      task ID, if none passed then generated by util\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "del",
     .synop = "Usage: " PROGRAM " del [OPTION]... [ID]...\n",
     .desc_short = "Delete task from project.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name (default is current)\n\
      -h      show this help and exit\n\
      -p PRJ  project name (default is current)\n\
      -q      do not write anything to standard error output\n\
      -y      delete task without confirmation\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      ID      task ID (default is current)\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "list",
     .synop = "Usage: " PROGRAM " list [OPTION]... [PRJ]...\n",
     .desc_short = "List project tasks.\n",
     .desc_long = "\n\
    Options:\n\
      -a      list all tasks\n\
      -b BRD  board name (default is current)\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
      -v      under development: show more verbose output\n\
      -t      show ONLY toggle switches (current and previous)\n\
      -H      show headers\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      COL     column name\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "move",
     .synop = "Usage: " PROGRAM " move [OPTION]... [SRC DST | SRC...]\n",
     .desc_short = "Move (rename) tasks (under development).\n",
     .desc_long = "\n\
    Options:\n\
      -d PRJ  destination project\n\
      -f      overwrite destination task (under development)\n\
      -s PRJ  source project\n\
      -T      treat all task IDs as source to move to project (under development)\n\
    \n\
    Arguments:\n\
      DST     destination task ID\n\
      PRJ     project name (default is current)\n\
      SRC     source task ID\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "prev",
     .synop = "Usage: " PROGRAM " prev [OPTION]...\n",
     .desc_short = "Switch to previous task.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name (default is current)\n\
      -h      show this help and exit\n\
      -p PRJ  project name (default is current)\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Return success if previous task and current project exists, otherwise fail\n"},
    {
     .tag = TAGBASIC,
     .name = "set",
     .synop = "Usage: " PROGRAM " set OPTION... [ID]...\n",
     .desc_short = "Set task unit values.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name (default is current)\n\
      -d      task description\n\
      -h      show this help and exit\n\
      -p PRJ  project name (default is current)\n\
      -q      do not write anything to standard error output\n\
      -t      task type\n\
      -P      task priority\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      ID      task ID (default is current)\n\
      PRJ     project name (default is current)\n\
    \n\
    Values:\n\
      Type    task, bugfix, feature, hotfix\n\
      Prio    lowest, low, mid, high, highest\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "show",
     .synop = "Usage: " PROGRAM " show [OPTION]... [ID]...\n",
     .desc_short = "Show task unit values.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name (default is current)\n\
      -h      show this help and exit\n\
      -k KEY  key to show (builtin or plugin)\n\
      -p PRJ  project name (default is current)\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      ID      task ID (default is current)\n\
      KEY     unit key to show\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "sync",
     .synop = "Usage: " PROGRAM " sync [OPTION]... [ID]...\n",
     .desc_short = "Synchronize (with) task.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name (default is current)\n\
      -n      do not update toggles\n\
      -h      show this help and exit\n\
      -p PRJ  project name (default is current)\n\
      -q      do not write anything to standard error output\n\
      -N      neither update toggles nor switch to task directory\n\
    \n\
    Arguments:\n\
      BRD     board name (default current)\n\
      ID      task ID (default is current)\n\
      PRJ     project name (default current)\n\
    \n\
    Exit status:\n\
    Under development\n"},

    {
     .tag = TAGOBJ,
     .name = "board",
     .synop = "Usage: " PROGRAM " board SUBCMD [OPTION] NAME\n",
     .desc_short = "Manage and show boards.\n",
     .desc_long = "\n\
    Arguments:\n\
      SUBCMD  board subcommand\n\
    \n\
    SUBCMD list:\n\
      add     Add a new board\n\
      del     Delete board with all tasks\n\
      list    List boards\n\
      move    Move (rename) boards\n\
      prev    Switch to previous board\n\
      set     Set board vaules\n\
      show    Show board info (under development)\n\
      sync    Switch to or synchronize (with) board\n\
    \n\
    Note:\n\
      Use '" PROGRAM " help board-SUBCMD' to get help on subcommands. \n\
      For example: " PROGRAM " help board-add\n\
    \n\
    Exit status:\n\
    The return status is return status of subcommand.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "board-add",
     .synop = "Usage: " PROGRAM " board add [OPTION] [NAME]...\n",
     .desc_short = "Add new board.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -n      do not switch to newly created project\n\
      -p PRJ  project name (default is current)\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    board name (autogenerated if not passed)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "board-del",
     .synop = "Usage: " PROGRAM " board del [OPTION] [NAME]...\n",
     .desc_short = "Delete board(s) from project.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -n      delete task without confirmation\n\
      -p PRJ  project name (default is current)\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    board name (autogenerated if not passed)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "board-list",
     .synop = "Usage: " PROGRAM " board list [OPTION]... [PRJ] \n",
     .desc_short = "List boards\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "board-move",
     .synop = "Usage: " PROGRAM " board move [OPTION] [SRC|DST]\n",
     .desc_short = "Move or renome board.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -p PRJ  project name (default is current)\n\
      -q      do not write anything to standard error output\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "board-prev",
     .synop = "Usage: " PROGRAM " board prev [OPTION]...\n",
     .desc_short = "Switch to previous board in current project.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -p PRJ  project name (default is current)\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGOBJCMD,
     .name = "board-set",
     .synop = "Usage: " PROGRAM " board set OPTION... [BRD]...\n",
     .desc_short = "Set task unit values.\n",
     .desc_long = "\n\
    Options:\n\
      -d      task description\n\
      -h      show this help and exit\n\
      -p PRJ  project name (default is current)\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGOBJCMD,
     .name = "board-show",
     .synop = "Usage: " PROGRAM " board show [OPTION]... [BRD]...\n",
     .desc_short = "Set task unit values.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name (default is current)\n\
      -h      show this help and exit\n\
      -k KEY  key to show (builtin or plugin)\n\
      -p PRJ  project name (default is current)\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      ID      task ID (default is current)\n\
      KEY     unit key to show\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGOBJCMD,
     .name = "board-sync",
     .synop = "Usage: " PROGRAM " board sync [OPTION]... [BRD]...\n",
     .desc_short = "Switch to or synchronize task.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -n      do not switch to task\n\
      -p PRJ  project name (default is current)\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      ID      task ID (default is current)\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},

    {
     .tag = TAGOBJ,
     .name = "column",
     .synop = "Usage: " PROGRAM " column SUBCMD [OPTION] ARGS\n",
     .desc_short = "Manage and show columns.\n",
     .desc_long = "\n\
    Arguments:\n\
      SUBCMD  column subcommand\n\
    \n\
    SUBCMD list:\n\
      list    List columns\n\
      move    Move task to column\n\
    \n\
    Note:\n\
      Use '" PROGRAM " help column-SUBCMD' to get help on subcommands. \n\
      For example: " PROGRAM " help column-list\n\
    \n\
    Exit status:\n\
    The return status is return status of subcommand.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "column-list",
     .synop = "Usage: " PROGRAM " column list [OPTION]\n",
     .desc_short = "List columns.\n",
     .desc_long = "\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "column-move",
     .synop = "Usage: " PROGRAM " column move [OPTION] [ID]...\n",
     .desc_short = "Move task to column.\n",
     .desc_long = "\n\
    \n\
    Options:\n\
      -b BRD  board name (default is current)\n\
      -c COL  column to move task to\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
      -p PRJ  project name (default is current)\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      COL     column name\n\
      ID      task ID, if none passed then generated by util\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},

    {
     .tag = TAGOBJ,
     .name = "project",
     .synop = "Usage: " PROGRAM " project SUBCMD [OPTION] NAME\n",
     .desc_short = "Manage and show projects.\n",
     .desc_long = "\n\
    Arguments:\n\
      SUBCMD  project subcommand\n\
    \n\
    SUBCMD list:\n\
      add     Add a new project\n\
      del     Delete project with all boards and tasks\n\
      list    List projects\n\
      prev    Switch to previous project\n\
      rename  Rename project\n\
      set     Set project vaules\n\
      show    Show project info (under development)\n\
      sync    Switch to or synchronize (with) project\n\
    \n\
    Note:\n\
      Use '" PROGRAM " help project-SUBCMD' to get help on subcommands. \n\
      For example: " PROGRAM " help project-add\n\
    \n\
    Exit status:\n\
    The return status is return status of subcommand.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "project-add",
     .synop = "Usage: " PROGRAM " project add [OPTION] NAME...\n",
     .desc_short = "Add new project(s).\n",
     .desc_long = "\n\
    Options:\n\
      -b      board name (default is 'board-000')\n\
      -h      show this help and exit\n\
      -n      do not switch to newly created project\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "project-del",
     .synop = "Usage: " PROGRAM " project del [OPTION] NAME...\n",
     .desc_short = "Delete project(s).\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -n      delete project without confirmation\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    project name (default current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "project-list",
     .synop = "Usage: " PROGRAM " project list [OPTION]\n",
     .desc_short = "List project(s).\n",
     .desc_long = "\n\
    \n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
      -v      under development: show more info\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "project-prev",
     .synop = "Usage: " PROGRAM " project prev\n",
     .desc_short = "Switch to previous project.\n",
     .desc_long = "\n\
    Arguments:\n\
      NAME    project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "project-rename",
     .synop = "Usage: " PROGRAM " project rename [OPTION]... SRC DST\n",
     .desc_short = "Rename project.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      SRC    source project name\n\
      DST    destination project name\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "project-set",
     .synop = "Usage: " PROGRAM " project set [OPTION] [NAME]...\n",
     .desc_short = "Set project unit values.\n",
     .desc_long = "\n\
    Arguments:\n\
      NAME    project name (default is current)\n\
    \n\
    Options:\n\
      -d      project description\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "project-show",
     .synop = "Usage: " PROGRAM " project show [OPTION] [NAME]...\n",
     .desc_short = "Show project(s) info.\n",
     .desc_long = "\n\
    \n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    project name (default current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "project-sync",
     .synop = "Usage: " PROGRAM " project sync [OPTION] NAME...\n",
     .desc_short = "Switch to or synchronize (with) project(s).\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -n      do not switch to project\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    project name (default current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
};

static void show_cmd_section(const char *title, const char *tag)
{
    const char *name, *desc;

    printf("\n" PADDING "%s:\n", title);
    for (int i = 0; i < ARRAY_SIZE(helptab); ++i) {
        if (strcmp(helptab[i].tag, tag) == 0) {
            name = helptab[i].name;
            desc = helptab[i].desc_short;
            printf(PADDING "  %-" xstr(CMDSIZ) "s - %s", name, desc);
        }
    }
}

int help_list_commands(void)
{
    printf("Usage: " PROGRAM " [OPTION]... COMMAND|PLUGIN\n");
    printf(PADDING "Run '" PROGRAM " help " PROGRAM "' to get more info.\n");

    show_cmd_section("System", TAGSYSTEM);
    show_cmd_section("Basic", TAGBASIC);
    show_cmd_section("Object", TAGOBJ);
    return 0;
}

int help_usage(const char *cmd)
{
    for (int i = 0; i < ARRAY_SIZE(helptab); ++i) {
        if (strcmp(helptab[i].name, cmd) == 0) {
            printf("%s", helptab[i].synop);
            printf("Try '" PROGRAM " help %s' for more info.\n", cmd);
            return 1;
        }
    }
    return elog(1, "%s: command not found", cmd);
}

int help_lookup(const char *cmd)
{
    int i, found;

    found = false;
    for (i = 0; i < ARRAY_SIZE(helptab); ++i) {
        if (strcmp(helptab[i].name, cmd) == 0) {
            found = true;
            if (helpctx.synop) {
                printf("%s", helptab[i].synop);
                continue;
            }
            if (helpctx.desc_short) {
                printf("%s - %s", cmd, helptab[i].desc_short);
                continue;
            }

            printf("%s", helptab[i].synop);
            printf("    %s", helptab[i].desc_short);
            printf("    %s", helptab[i].desc_long);
            break;
        }
    }
    return found == true ? 0 : 1;
}

int tec_cli_help(int argc, char **argv, tec_ctx_t * ctx)
{
    char c;
    int i, status;

    status = LIBTEC_OK;
    while ((c = getopt(argc, argv, ":ds")) != -1) {
        switch (c) {
        case 'd':
            helpctx.desc_short = true;
            helpctx.synop = false;
            helpctx.desc_long = false;
            break;
        case 's':
            helpctx.synop = true;
            helpctx.desc_short = false;
            helpctx.desc_long = false;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        };
    }

    if (optind == argc)
        return help_list_commands();

    for (i = optind; i < argc; ++i)
        if ((status = help_lookup(argv[i])))
            elog(1, "'%s': no such builtin command", argv[i]);
    return status;
}
