#include <stdio.h>
#include <string.h>

#include "help.h"
#include "cli.h"

#define PADDING     "    "
#define SYSTEM      "system"
#define TAGOBJ      "bin-object"
#define TAGOBJCMD   "bin-object-cmd"
#define TAGSYSTEM   "bin-system"
#define TAGBASIC    "bin-basic"

struct helpctx {
    int synop;
    int desc_short;
    int desc_long;
};

struct helpctx helpctx = {
    .synop = FALSE,
    .desc_short = FALSE,
    .desc_long = FALSE,
};

struct help helptab[] = {
    {
     .tag = SYSTEM,
     .name = "tman",
     .synop = "Usage: " PROGRAM " [OPTION]... COMMAND|PLUGIN\n",
     .desc_short = "Terminal project and task manager.\n",
     .desc_long = "\n\
    Options:\n\
      -C TOG  enbale colors (default: disabled)\n\
      -D TOG  enbale debug mode (default: disabled)\n\
      -h      show this help and exit\n\
      -F DIR  path to the config file (under development)\n\
      -H TOG  enbale hooks (default: disabled)\n\
      -P DIR  directory where plugins are stored\n\
      -T DIR  directory where tasks are stored\n\
      -V      show version and exit\n\
    \n\
    Arguments:\n\
      DIR     path to directory\n\
      TOG     can be either 'on' or 'off'\n\
    \n\
    Notes:\n\
    It's more convient to set options in config file. This way no need\n\
    to type them every time.\n\
    \n\
    Exit status:\n\
    Return status of builtin command or plugin\n"},
    {
     .tag = TAGSYSTEM,
     .name = "cfg",
     .synop = "Usage: " PROGRAM " cfg [OPTION]... [COMMAND]\n",
     .desc_short = "Manage system configuration file.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      SUBCMD  project subcommand\n\
    \n\
    SUBCMD list:\n\
      set     Set config value (under developmnt)\n\
      show    Show config values\n\
    \n\
    WARNING: when setting new values, all comments in config file will be lost\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGSYSTEM,
     .name = "fsck",
     .synop = "Usage: " PROGRAM " fsck\n",
     .desc_short = "Check and repair a system (under development).\n",
     .desc_long = "\n\
    UNDER DEVELOPMENT\n\
    \n\
    Options:\n\
      -s      under development: soft fix (without losing any user data)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGSYSTEM,
     .name = "help",
     .synop = "Usage: " PROGRAM " help [OPTION] [CMD]\n",
     .desc_short = "Show help message for command.\n",
     .desc_long = "\n\
    If no CMD passed, list all commands with short description.\n\
    \n\
    Options:\n\
      -d      output short description for each topic\n\
      -s      output only a short usage synopsis for each topic matching\n\
    \n\
    Arguments:\n\
      CMD     builtin command\n\
    \n\
    Exit status:\n\
    Returns success unless PATTERN is not found or an invalid option is given.\n"},
    {
     .tag = TAGSYSTEM,
     .name = "init",
     .synop = "Usage: " PROGRAM " init\n",
     .desc_short = "Init directory structure.\n",
     .desc_long = "\n\
    Exit status:\n\
    Under development\n"},

    {
     .tag = TAGBASIC,
     .name = "add",
     .synop = "Usage: " PROGRAM " add [OPTION]... [ID]...\n",
     .desc_short = "Add a new task to project.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name\n\
      -h      show this help and exit\n\
      -n      don't switch to newly created task\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      ID      task ID, if none passed then generated by util\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "del",
     .synop = "Usage: " PROGRAM " del [OPTION]... [ID]...\n",
     .desc_short = "Delete task from project.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name\n\
      -h      show this help and exit\n\
      -n      delete task without confirmation\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      ID      task ID (default current)\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "list",
     .synop = "Usage: " PROGRAM " list [OPTION]... [PRJ]...\n",
     .desc_short = "List project tasks.\n",
     .desc_long = "\n\
    Options:\n\
      -a      list all tasks expect for done\n\
      -b BRD  board name\n\
      -c COL  specify what column to list task from\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
      -v      under development: show more verbose output\n\
      -D      show ONLY done tasks\n\
      -H      show headers\n\
      -S      show ONLY toggle switches (current and previous)\n\
      -T      show ONLY todo tasks\n\
    \n\
    Arguments:\n\
      BRD     board name (default current)\n\
      COL     column name\n\
      PRJ     project name (default current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "move",
     .synop = "Usage: " PROGRAM " move [OPTION]... [SRC DST | SRC...]\n",
     .desc_short = "Move (rename) tasks.\n",
     .desc_long = "\n\
    Options:\n\
      -d PRJ  destination project\n\
      -f      overwrite destination task (under development)\n\
      -s PRJ  source project\n\
      -T      treat all task IDs as source to move to project (under development)\n\
    \n\
    Arguments:\n\
      DST     destination task ID\n\
      PRJ     project name (default is current)\n\
      SRC     source task ID\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "prev",
     .synop = "Usage: " PROGRAM " prev [OPTION]...\n",
     .desc_short = "Switch to previous task.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name\n\
      -h      show this help and exit\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Return success if previous task and current project exists, otherwise fail\n"},
    {
     .tag = TAGBASIC,
     .name = "set",
     .synop = "Usage: " PROGRAM " set OPTION... [ID]...\n",
     .desc_short = "Set task unit values.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name\n\
      -d      task description\n\
      -h      show this help and exit\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
      -t      task type\n\
      -P      task priority\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      ID      task ID (default current)\n\
      PRJ     project name (default is current)\n\
    \n\
    Values:\n\
      Type    task, bugfix, feature, hotfix\n\
      Prio    lowest, low, mid, high, highest\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "show",
     .synop = "Usage: " PROGRAM " show [OPTION]... [ID]...\n",
     .desc_short = "Show task info.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name\n\
      -h      show this help and exit\n\
      -k KEY  key to show (builtin or plugin)\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      ID      task ID (default current)\n\
      KEY     unit key to show\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGBASIC,
     .name = "sync",
     .synop = "Usage: " PROGRAM " sync [OPTION]... [ID]...\n",
     .desc_short = "Switch to or synchronize task.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name\n\
      -h      show this help and exit\n\
      -n      do not switch to task\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default current)\n\
      ID      task ID (default current)\n\
      PRJ     project name (default current)\n\
    \n\
    Exit status:\n\
    Under development\n"},

    {
     .tag = TAGOBJ,
     .name = "brd",
     .synop = "Usage: " PROGRAM " brd SUBCMD [OPTION] NAME\n",
     .desc_short = "Manage and show boards.\n",
     .desc_long = "\n\
    Arguments:\n\
      SUBCMD  board subcommand\n\
    \n\
    SUBCMD list:\n\
      add     Add a new board\n\
      del     Delete board with all tasks\n\
      export  Export tasks from board (into project)\n\
      import  Import tasks into board (out of project)\n\
      list    List boards\n\
      move    Move (rename) boards\n\
      prev    Switch to previous board\n\
      set     Set board vaules\n\
      show    Show board info (under development)\n\
      sync    Switch to or synchronize (with) board\n\
    \n\
    Note:\n\
      Use '" PROGRAM " help brd-SUBCMD' to get help on subcommands. \n\
      For example: " PROGRAM " help brd-add\n\
    \n\
    Exit status:\n\
    The return status is return status of subcommand.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "brd-add",
     .synop = "Usage: " PROGRAM " brd add [OPTION] [NAME]...\n",
     .desc_short = "Add new board.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -n      do not switch to newly created project\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    board name (autogenerated if not passed)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "brd-del",
     .synop = "Usage: " PROGRAM " brd del [OPTION] [NAME]...\n",
     .desc_short = "Delete board(s) from project.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -n      delete task without confirmation\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    board name (autogenerated if not passed)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "brd-export",
     .synop = "Usage: " PROGRAM " brd export [OPTION] [NAME]...\n",
     .desc_short = "Export tasks from board (into project)\n",
     .desc_long = "\n\
    THIS FEATURE IS UNDER DEVELOPMENT\n\
    \n\
    Options:\n\
      -h      show this help and exit\n\
      -n      do not switch to newly created project\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    board name (autogenerated if not passed)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "brd-import",
     .synop = "Usage: " PROGRAM " brd import [OPTION] [NAME]...\n",
     .desc_short = "Import tasks into board (inside project)\n",
     .desc_long = "\n\
    THIS FEATURE IS UNDER DEVELOPMENT\n\
    \n\
    Options:\n\
      -h      show this help and exit\n\
      -n      do not switch to newly created project\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    board name (autogenerated if not passed)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "brd-list",
     .synop = "Usage: " PROGRAM " brd list [OPTION]... [PRJ] \n",
     .desc_short = "List boards\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "brd-move",
     .synop = "Usage: " PROGRAM " brd move [OPTION] [SRC|DST]\n",
     .desc_short = "Move or renome board.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "brd-prev",
     .synop = "Usage: " PROGRAM " brd prev [OPTION]...\n",
     .desc_short = "Switch to previous board in current project.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGOBJCMD,
     .name = "brd-set",
     .synop = "Usage: " PROGRAM " brd set OPTION... [BRD]...\n",
     .desc_short = "Set task unit values.\n",
     .desc_long = "\n\
    Options:\n\
      -d      task description\n\
      -h      show this help and exit\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGOBJCMD,
     .name = "brd-show",
     .synop = "Usage: " PROGRAM " brd show [OPTION]... [BRD]...\n",
     .desc_short = "Set task unit values.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name\n\
      -h      show this help and exit\n\
      -k KEY  key to show (builtin or plugin)\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      ID      task ID (default current)\n\
      KEY     unit key to show\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGOBJCMD,
     .name = "brd-sync",
     .synop = "Usage: " PROGRAM " brd sync [OPTION]... [BRD]...\n",
     .desc_short = "Switch to or synchronize task.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -n      do not switch to task\n\
      -p PRJ  project name\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default current)\n\
      ID      task ID (default current)\n\
      PRJ     project name (default current)\n\
    \n\
    Exit status:\n\
    Under development\n"},

    {
     .tag = TAGOBJ,
     .name = "flow",
     .synop = "Usage: " PROGRAM " flow SUBCMD [OPTION]... [ID]\n",
     .desc_short = "Manage and show workflow.\n",
     .desc_long = "\n\
    Arguments:\n\
      SUBCMD  flow subcommand\n\
    \n\
    SUBCMD list:\n\
      list     List columns \n\
      move     Move task to column\n\
      next     Move task to next column in workflow (under development)\n\
      prev     Move task to previous column in workflow (under development)\n\
    \n\
    Note:\n\
      Use '" PROGRAM " help flow-SUBCMD' to get help on subcommands. \n\
      For example: " PROGRAM " help flow-list\n\
    \n\
    Exit status:\n\
    Under development\n"},
    {
     .tag = TAGOBJCMD,
     .name = "flow-list",
     .synop = "Usage: " PROGRAM " flow list [OPTION]\n",
     .desc_short = "List columns.\n",
     .desc_long = "\n\
    Options:\n\
      -b BRD  board name (under development)\n\
      -h      show this help and exit\n\
      -p PRJ  project name (under development)\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      BRD     board name (default is current)\n\
      PRJ     project name (default is current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "flow-move",
     .synop = "Usage: " PROGRAM " flow move [OPTION] [ID]...\n",
     .desc_short = "Move task to column.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Note:\n\
      Default column to move to is 'todo'.\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "flow-next",
     .synop = "Usage: " PROGRAM " flow next [OPTION]\n",
     .desc_short = "Move task to next column in workflow.\n",
     .desc_long = "\n\
    \n\
    UNDER DEVELOPMENT\n\
    \n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "flow-prev",
     .synop = "Usage: " PROGRAM " flow prev [OPTION]\n",
     .desc_short = "Move task to previous column in workflow.\n",
     .desc_long = "\n\
    \n\
    UNDER DEVELOPMENT\n\
    \n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Exit status:\n\
    Under development.\n"},

    {
     .tag = TAGOBJ,
     .name = "prj",
     .synop = "Usage: " PROGRAM " prj SUBCMD [OPTION] NAME\n",
     .desc_short = "Manage and show projects.\n",
     .desc_long = "\n\
    Arguments:\n\
      SUBCMD  project subcommand\n\
    \n\
    SUBCMD list:\n\
      add     Add a new project\n\
      del     Delete project with all boards and tasks\n\
      list    List projects\n\
      prev    Switch to previous project\n\
      rename  Rename project\n\
      set     Set project vaules\n\
      show    Show project info (under development)\n\
      sync    Switch to or synchronize (with) project\n\
    \n\
    Note:\n\
      Use '" PROGRAM " help prj-SUBCMD' to get help on subcommands. \n\
      For example: " PROGRAM " help prj-add\n\
    \n\
    Exit status:\n\
    The return status is return status of subcommand.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "prj-add",
     .synop = "Usage: " PROGRAM " prj add [OPTION] NAME...\n",
     .desc_short = "Add new project(s).\n",
     .desc_long = "\n\
    Options:\n\
      -b      board name (default is 'brd-000')\n\
      -h      show this help and exit\n\
      -n      do not switch to newly created project\n\
      -q      do not write anything to standard error output\n\
      -B      do not create default board\n\
    \n\
    Arguments:\n\
      NAME    project name\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "prj-del",
     .synop = "Usage: " PROGRAM " prj del [OPTION] NAME...\n",
     .desc_short = "Delete project(s).\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -n      delete project without confirmation\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    project name (default current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "prj-list",
     .synop = "Usage: " PROGRAM " prj list [OPTION]\n",
     .desc_short = "List project(s).\n",
     .desc_long = "\n\
    \n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
      -v      under development: show more info\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "prj-prev",
     .synop = "Usage: " PROGRAM " prj prev\n",
     .desc_short = "Switch to previous project.\n",
     .desc_long = "\n\
    Arguments:\n\
      NAME    project name\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "prj-rename",
     .synop = "Usage: " PROGRAM " prj rename [OPTION]... SRC DST\n",
     .desc_short = "Rename project.\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      SRC    source project name\n\
      DST    destination project name\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "prj-set",
     .synop = "Usage: " PROGRAM " prj set [OPTION] [NAME]...\n",
     .desc_short = "Set project unit values.\n",
     .desc_long = "\n\
    Arguments:\n\
      NAME    project name\n\
    \n\
    Options:\n\
      -d      project description\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "prj-show",
     .synop = "Usage: " PROGRAM " prj show [OPTION] [NAME]...\n",
     .desc_short = "Show project(s) info.\n",
     .desc_long = "\n\
    \n\
    Options:\n\
      -h      show this help and exit\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    project name (default current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
    {
     .tag = TAGOBJCMD,
     .name = "prj-sync",
     .synop = "Usage: " PROGRAM " prj sync [OPTION] NAME...\n",
     .desc_short = "Switch to or synchronize (with) project(s).\n",
     .desc_long = "\n\
    Options:\n\
      -h      show this help and exit\n\
      -n      do not switch to project\n\
      -q      do not write anything to standard error output\n\
    \n\
    Arguments:\n\
      NAME    project name (default current)\n\
    \n\
    Exit status:\n\
    Under development.\n"},
};

static void show_cmd_section(const char *title, const char *tag)
{
    const char *name, *desc;

    printf("\n" PADDING "%s:\n", title);
    for (int i = 0; i < ARRAY_SIZE(helptab); ++i) {
        if (strcmp(helptab[i].tag, tag) == 0) {
            name = helptab[i].name;
            desc = helptab[i].desc_short;
            printf(PADDING "  %-6s - %s", name, desc);
        }
    }
}

int help_list_commands(void)
{
    printf("Usage: " PROGRAM " [OPTION]... COMMAND|PLUGIN\n"
           PADDING "Run '" PROGRAM " help " PROGRAM "' to get more info.\n");

    show_cmd_section("System", TAGSYSTEM);
    show_cmd_section("Basic", TAGBASIC);
    show_cmd_section("Object", TAGOBJ);
    return LIBTMAN_OK;
}

int help_usage(const char *cmd)
{
    for (int i = 0; i < ARRAY_SIZE(helptab); ++i) {
        if (strcmp(helptab[i].name, cmd) == 0) {
            printf("%s", helptab[i].synop);
            printf("Try '" PROGRAM " help %s' for more info.\n", cmd);
            return 1;
        }
    }
    return elog(1, "%s: command not found", cmd);
}

int help_lookup(const char *cmd)
{
    int i, found;

    if (cmd == NULL)
        return help_list_commands();

    found = 0;
    for (i = 0; i < ARRAY_SIZE(helptab); ++i) {
        if (strcmp(helptab[i].name, cmd) == 0) {
            found = 1;
            if (helpctx.synop) {
                printf("%s", helptab[i].synop);
                continue;
            }
            if (helpctx.desc_short) {
                printf("%s - %s", cmd, helptab[i].desc_short);
                continue;
            }

            printf("%s", helptab[i].synop);
            printf("    %s", helptab[i].desc_short);
            printf("    %s", helptab[i].desc_long);
            break;
        }
    }
    if (!found)
        return emod_set(LIBTMAN_CMD_BIN);
    return LIBTMAN_OK;
}

int tman_cli_help(int argc, char **argv, tman_ctx_t * ctx)
{
    char c;
    int i, status;

    while ((c = getopt(argc, argv, ":ds")) != -1) {
        switch (c) {
        case 'd':
            helpctx.desc_short = TRUE;
            helpctx.synop = FALSE;
            helpctx.desc_long = FALSE;
            break;
        case 's':
            helpctx.synop = TRUE;
            helpctx.desc_short = FALSE;
            helpctx.desc_long = FALSE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        };
    }

    if (optind == argc)
        return help_list_commands();

    for (i = optind; i < argc; ++i) {
        if ((status = help_lookup(argv[i])) != LIBTMAN_OK)
            elog(status, "%s: %s", argv[i], tman_strerror());
    }
    return status;
}
