#include <ctype.h>
#include <string.h>
#include <dirent.h>

#include "cli.h"
#include "aux/config.h"
#include "aux/toggle.h"

static int generate_units(tec_ctx_t * ctx, char *project)
{
    struct tec_unit *units = NULL;
    char desc[100] = "autogenerated desciption for project ";

    strcat(desc, project);
    units = tec_unit_add(units, "desc", desc);
    ctx->units = units;
    return 0;
}

static int valid_desc(const char *val)
{
    if (!isalnum(*val++))
        return FALSE;
    for (; *val; ++val)
        if (!(isalnum(*val) || isspace(*val) || *val == '_' || *val == '-'))
            return FALSE;
    return isalnum(*--val) != 0;
}

// TODO: Find a good error message in case option fails.  */
static int _project_add(int argc, char **argv, tec_ctx_t * ctx)
{
    char c;
    tec_arg_t args;
    int switch_dir, switch_project;
    int i, quiet, showhelp, status;
    const char *errfmt = "cannot add project '%s': %s";
    const char *errfmt_board = "cannot add board '%s': %s";

    status = LIBTEC_OK;
    showhelp = quiet = FALSE;
    switch_dir = switch_project = TRUE;
    args.project = args.board = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":b:hnqN")) != -1) {
        switch (c) {
        case 'b':
            args.board = optarg;
            break;
        case 'h':
            showhelp = TRUE;
            break;
        case 'n':
            switch_project = FALSE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case 'N':
            switch_dir = FALSE;
            switch_project = FALSE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("project-add");

    if (optind == argc)
        return elog(1, "project name required");
    else if ((ctx->column = generate_column("todo")) == NULL) {
        if (quiet == FALSE)
            elog(1, "could not generate column");
        return 1;
    }

    /* Set default board name to create.  */
    if (args.board == NULL)
        args.board = "board";

    for (i = optind; i < argc; ++i) {
        args.project = argv[i];

        if (is_valid_length(args.project, PRJSIZ) == FALSE) {
            if (quiet == FALSE)
                elog(status, errfmt, args.project, "project name is too long");
            continue;
        } else if ((status = tec_project_valid(teccfg.base.task, &args))) {
            if (quiet == FALSE)
                elog(status, errfmt, args.project, tec_strerror(status));
            continue;
        } else if (!(status = tec_project_exist(teccfg.base.task, &args))) {
            char *project = args.project;
            if (quiet == FALSE)
                elog(status, errfmt, project, tec_strerror(LIBTEC_PRJ_EXISTS));
            continue;
        }

        if ((status = tec_board_valid(teccfg.base.task, &args))) {
            if (quiet == FALSE)
                elog(status, errfmt_board, args.board, tec_strerror(status));
            continue;
        } else if (is_valid_length(args.board, BRDSIZ) == FALSE) {
            if (quiet == FALSE)
                elog(status, errfmt_board, args.board,
                     "board name is too long");
            continue;
        } else if (!(status = tec_board_exist(teccfg.base.task, &args))) {
            if (quiet == FALSE)
                elog(status, errfmt_board, args.board,
                     tec_strerror(LIBTEC_BRD_EXISTS));
            continue;
        }

        if (generate_units(ctx, args.project)) {
            if (quiet == FALSE)
                elog(1, errfmt, args.project, "unit generation failed");
            continue;
        }

        if ((status = tec_project_add(teccfg.base.task, &args, ctx))) {
            if (quiet == FALSE)
                elog(1, errfmt, argv[i], tec_strerror(status));
            continue;
        } else if ((status = tec_board_add(teccfg.base.task, &args, ctx))) {
            if (quiet == FALSE)
                elog(1, errfmt, argv[i], tec_strerror(status));
            continue;
        }
        ctx->units = tec_unit_free(ctx->units);
    }

    ctx->column = tec_unit_free(ctx->column);

    if ((switch_project && status == LIBTEC_OK)
        && toggle_project_set_curr(teccfg.base.task, &args)) {
        if (quiet == FALSE)
            elog(status, "could not update project toggles");
        return 1;
    } else if ((switch_project && status == LIBTEC_OK)
               && toggle_board_set_curr(teccfg.base.task, &args)) {
        if (quiet == FALSE)
            elog(status, "could not update board toggles");
        return 1;
    }

    return (switch_dir
            && status == LIBTEC_OK) ? tec_pwd_project(&args) : status;
}

static int _project_del(int argc, char **argv, tec_ctx_t * ctx)
{
    char c;
    tec_arg_t args;
    const char *errfmt = "cannot delete project: %s";
    int i, choice, quiet, showhelp, showprompt, status;

    showprompt = TRUE;
    choice = quiet = showhelp = FALSE;
    args.project = args.board = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":b:hnq")) != -1) {
        switch (c) {
        case 'b':
            args.board = optarg;
            break;
        case 'h':
            showhelp = TRUE;
            break;
        case 'n':
            showprompt = FALSE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("project-del");

    if (showprompt) {
        printf("Are you sure to delete projects(s)? [y/N] ");
        choice = getchar();
        if (choice != 'y' && choice != 'Y') {
            return 0;
        }
    }

    i = optind;
    do {
        args.project = argv[i];
        if ((status =
             tec_project_del(teccfg.base.task, &args, ctx)) != LIBTEC_OK) {
            if (quiet == FALSE)
                elog(status, errfmt, argv[i], tec_strerror(status));
        }
    } while (++i < argc);

    // TODO: update current directory if current project got deleted.
    return status == LIBTEC_OK ? tec_pwd_project(&args) : status;
}

static int _project_list(int argc, char **argv, tec_ctx_t * ctx)
{
    int c, quiet, status;
    tec_arg_t args;

    quiet = FALSE;
    args.project = args.board = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":q")) != -1) {
        switch (c) {
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if ((status = tec_project_list(teccfg.base.task, &args, ctx))) {
        if (quiet == FALSE) {
            const char *errfmt = "cannot list project(s) '%s': %s";
            elog(status, errfmt, "PRJ", tec_strerror(status));
            return status;
        }
    }

    for (tec_list_t * obj = ctx->list; obj != NULL; obj = obj->next) {
        LIST_PROJECT_UNITS("mark", obj->name, "some project description");
    }
    ctx->list = tec_list_free(ctx->list);
    return status;
}

static int _project_prev(int argc, char **argv, tec_ctx_t * ctx)
{
    tec_arg_t args;
    char c, *errfmt;
    int quiet, showhelp, status;

    quiet = showhelp = FALSE;
    args.project = args.board = args.taskid = NULL;
    errfmt = "cannot switch to previous project '%s': %s";
    while ((c = getopt(argc, argv, ":hq")) != -1) {
        switch (c) {
        case 'h':
            showhelp = TRUE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp == TRUE)
        return help_usage("project-prev");

    if ((status = toggle_project_get_prev(teccfg.base.task, &args))) {
        if (quiet == FALSE)
            elog(status, errfmt, "NOPREV", "no previous project");
        return status;
    } else if ((status = toggle_project_get_curr(teccfg.base.task, &args))) {
        if (quiet == FALSE)
            elog(status, errfmt, "NOCURR", "no current project");
        return status;
    }

    if (toggle_project_swap(teccfg.base.task, &args)) {
        if (quiet == FALSE)
            elog(1, "could not update toggle");
        return 1;
    }

    return status == LIBTEC_OK ? tec_pwd_project(&args) : status;
}

static int _project_rename(int argc, char **argv, tec_ctx_t * ctx)
{
    char *errfmt;
    tec_arg_t src, dst;
    int c, quiet, showhelp, status;

    quiet = showhelp = FALSE;
    errfmt = "could not rename project: %s";
    src.project = src.board = src.taskid = NULL;
    dst.project = dst.board = dst.taskid = NULL;
    while ((c = getopt(argc, argv, ":hq")) != -1) {
        switch (c) {
        case 'h':
            showhelp = TRUE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("project-rename");

    if (argc - optind != 2)
        return elog(1, "source or destination project name missing");

    src.project = argv[optind];
    dst.project = argv[optind + 1];

    /* TODO: trigger hooks if any */

    if ((status = check_arg_project(&src, errfmt, quiet)))
        return status;
    else if ((status = check_arg_project(&src, errfmt, quiet)))
        return status;
    else if (tec_project_exist(teccfg.base.task, &dst)) {
        if (quiet == FALSE)
            elog(1, "'%s': destination project exists\n", dst.project);
        return status;
    }

    if ((status = tec_project_rename(teccfg.base.task, &src, &dst, NULL))) {
        if (quiet == FALSE)
            elog(status, errfmt, tec_strerror(status));
        return status;
    }
    return tec_pwd_project(&dst);
}

static int _project_set(int argc, char **argv, tec_ctx_t * ctx)
{
    tec_arg_t args;
    int atleast_one_key_set;
    int c, i, quiet, showhelp;
    const char *errfmt = "could not set project unit value '%s': %s";

    quiet = showhelp = FALSE;
    atleast_one_key_set = FALSE;
    args.project = args.board = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":b:d:hq")) != -1) {
        switch (c) {
        case 'b':
            args.board = optarg;
            break;
        case 'd':
            if (valid_desc(optarg) == FALSE) {
                elog(1, "invalid description '%s'", optarg);
                help_usage("project-set");
                return 1;
            }
            atleast_one_key_set = TRUE;
            ctx->units = tec_unit_add(ctx->units, "desc", optarg);
            break;
        case 'h':
            showhelp = TRUE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("project-set");
    if (atleast_one_key_set == FALSE) {
        elog(1, "gotta supply one of the options");
        help_usage("project-set");
        return 1;
    }

    i = optind;
    do {
        int status;
        args.project = argv[i];

        if ((status = tec_project_set(teccfg.base.task, &args, ctx))) {
            if (quiet == FALSE)
                elog(status, errfmt, argv[i], tec_strerror(status));
        }
    } while (++i < argc);

    ctx->units = tec_unit_free(ctx->units);
    return 0;
}

// roach: maybe it'll be useful
static int _project_show(int argc, char **argv, tec_ctx_t * ctx)
{
    tec_arg_t args;
    int c, i, quiet, showhelp, status;
    struct tec_unit *unitbin, *unitpgn;
    const char *errfmt = "cannot show project units '%s': %s";

    unitbin = unitpgn = NULL;
    quiet = showhelp = FALSE;
    args.project = args.board = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":b:hq")) != -1) {
        switch (c) {
        case 'b':
            args.board = optarg;
            break;
        case 'h':
            showhelp = TRUE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("project-show");

    i = optind;
    do {
        args.project = argv[i];
        if ((status = tec_project_get(teccfg.base.task, &args, ctx))) {
            if (quiet == FALSE)
                elog(status, errfmt, argv[i], tec_strerror(status));
            continue;
        }

        printf("%-7s : %s\n", "project", args.project);
        for (unitbin = ctx->units; unitbin; unitbin = unitbin->next)
            printf("%-7s : %s\n", unitbin->key, unitbin->val);

        // TODO: add plugin output
    } while (++i < argc);

    return status;
}

static int _project_sync(int argc, char **argv, tec_ctx_t * ctx)
{
    tec_arg_t args;
    int c, i, quiet, showhelp, status;
    const char *errfmt = "cannot switch to '%s': %s";
    int switch_toggle, switch_dir;

    quiet = showhelp = FALSE;
    switch_toggle = switch_dir = TRUE;
    args.project = args.board = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":b:hnqN")) != -1) {
        switch (c) {
        case 'b':
            args.board = optarg;
            break;
        case 'h':
            showhelp = TRUE;
            break;
        case 'n':
            switch_toggle = FALSE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case 'N':
            switch_dir = FALSE;
            switch_toggle = FALSE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("project-sync");

    i = optind;
    do {
        args.project = argv[i];

        if ((status = check_arg_project(&args, errfmt, quiet)))
            continue;
    } while (++i < argc);

    if (status == LIBTEC_OK && switch_toggle == TRUE) {
        if (toggle_project_set_curr(teccfg.base.task, &args)
            && quiet == FALSE)
            status = elog(1, "could not update project toggles");
    }

    return status == LIBTEC_OK && switch_dir ? tec_pwd_project(&args) : status;
}

static const builtin_t project_commands[] = {
    {.name = "add",.func = &_project_add},
    {.name = "del",.func = &_project_del},
    {.name = "list",.func = &_project_list},
    {.name = "prev",.func = &_project_prev},
    {.name = "rename",.func = &_project_rename},
    {.name = "set",.func = &_project_set},
    {.name = "show",.func = &_project_show},
    {.name = "sync",.func = &_project_sync},
};

int tec_cli_project(int argc, char **argv, tec_ctx_t * ctx)
{
    char *cmd = argv[1] != NULL ? argv[1] : "list";

    for (int i = 0; i < ARRAY_SIZE(project_commands); ++i)
        if (strcmp(cmd, project_commands[i].name) == 0)
            return project_commands[i].func(argc - 1, argv + 1, ctx);

    return elog(1, "'%s': no such project command", cmd);
}
