#include <ctype.h>
#include <string.h>
#include <dirent.h>

#include "cli.h"

static int generate_units(tman_ctx_t * ctx, char *prj)
{
    struct tman_unit *units = NULL;
    char desc[100] = "autogenerated desciption for project ";

    strcat(desc, prj);
    units = tman_unit_add(units, "desc", desc);
    ctx->units = units;
    return 0;
}

static int valid_desc(const char *val)
{
    if (!isalnum(*val++))
        return FALSE;
    for (; *val; ++val)
        if (!(isalnum(*val) || isspace(*val) || *val == '_' || *val == '-'))
            return FALSE;
    return isalnum(*--val) != 0;
}

// TODO: Find a good error message in case option fails.  */
static int _project_add(int argc, char **argv, tman_ctx_t * ctx)
{
    char c;
    tman_arg_t args;
    const char *errfmt = "cannot add project '%s': %s";
    int i, quiet, showhelp, status;

    status = LIBTMAN_OK;
    showhelp = quiet = FALSE;
    args.project = args.board = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":b:hnqB")) != -1) {
        switch (c) {
        case 'b':
            args.board = optarg;
            break;
        case 'h':
            showhelp = TRUE;
            break;
        case 'n':
            //opt.prj_switch = FALSE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case 'B':
            return elog(1, "option `-B': under development");
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("project-add");

    if (optind == argc)
        return elog(1, "project name required");
    else if ((ctx->column = generate_column("todo")) == NULL) {
        if (quiet == FALSE)
            elog(1, "could not generate column");
        return 1;
    }

    /* Set default board name to create.  */
    if (args.board == NULL)
        args.board = "brd-000";

    for (i = optind; i < argc; ++i) {
        args.project = argv[i];

        if (generate_units(ctx, args.project)) {
            if (quiet == FALSE)
                elog(1, errfmt, args.project, "unit generation failed");
            continue;
        } else if ((status = tman_project_add(ctx, &args)) != LIBTMAN_OK) {
            if (quiet == FALSE)
                elog(1, errfmt, argv[i], tman_strerror(status));
            continue;
        }
        // TODO: add support to add default board when project gets created
        // TODO: create default board if option to use boards is set in config
        ctx->units = tman_unit_free(ctx->units);
    }
    ctx->column = tman_unit_free(ctx->column);

    //return opt.prj_switch && status == LIBTMAN_OK ? tman_pwd_project() : status;
    //return status == LIBTMAN_OK ? tman_pwd_project() : status;
    return 0;
}

static int _project_del(int argc, char **argv, tman_ctx_t * ctx)
{
    char c;
    tman_arg_t args;
    const char *errfmt = "cannot delete project: %s";
    int i, choice, quiet, showhelp, showprompt, status;

    showprompt = TRUE;
    choice = quiet = showhelp = FALSE;
    args.project = args.board = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":b:hnq")) != -1) {
        switch (c) {
        case 'b':
            args.board = optarg;
            break;
        case 'h':
            showhelp = TRUE;
            break;
        case 'n':
            showprompt = FALSE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("project-del");

    if (showprompt) {
        printf("Are you sure to delete projects(s)? [y/N] ");
        choice = getchar();
        if (choice != 'y' && choice != 'Y') {
            return 0;
        }
    }

    i = optind;
    do {
        args.project = argv[i];
        if ((status = tman_project_del(ctx, &args)) != LIBTMAN_OK) {
            if (quiet == FALSE)
                elog(status, errfmt, argv[i], tman_strerror(status));
        }
    } while (++i < argc);

    dlog(1, "prj_del: status = %d", status);

    // TODO: update current directory if current prj got deleted.
    return status == LIBTMAN_OK ? tman_pwd_project() : status;
}

static int _project_list(int argc, char **argv, tman_ctx_t * ctx)
{
    int c, quiet, status;

    quiet = FALSE;
    while ((c = getopt(argc, argv, ":q")) != -1) {
        switch (c) {
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if ((status = tman_project_list(ctx)) != LIBTMAN_OK) {
        if (quiet == FALSE) {
            const char *errfmt = "cannot list project(s) '%s': %s";
            elog(status, errfmt, "PRJ", tman_strerror(status));
        }
    }
    return status;
}

static int _project_prev(int argc, char **argv, tman_ctx_t * ctx)
{
    return elog(1, "under development");
}

static int _project_rename(int argc, char **argv, tman_ctx_t * ctx)
{
    int c, quiet, showhelp, status;
    tman_arg_t src, dst;

    quiet = showhelp = FALSE;
    src.project = src.board = src.taskid = NULL;
    dst.project = dst.board = dst.taskid = NULL;
    while ((c = getopt(argc, argv, ":hq")) != -1) {
        switch (c) {
        case 'h':
            showhelp = TRUE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("prj-rename");

    if (argc - optind != 2)
        return elog(1, "source or destination project name missing");

    src.project = argv[optind];
    dst.project = argv[optind + 1];

    /* TODO: trigger hooks if any */

    if ((status = tman_project_rename(NULL, &src, &dst))) {
        if (quiet == FALSE)
            elog(status, "could not rename project: %s", tman_strerror(status));
    }
    return tman_pwd_project();
}

static int _project_set(int argc, char **argv, tman_ctx_t * ctx)
{
    tman_arg_t args;
    int atleast_one_key_set;
    int c, i, quiet, showhelp;
    const char *errfmt = "could not set project unit value '%s': %s";

    quiet = showhelp = FALSE;
    atleast_one_key_set = FALSE;
    args.project = args.board = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":b:d:hq")) != -1) {
        switch (c) {
        case 'b':
            args.board = optarg;
            break;
        case 'd':
            if (valid_desc(optarg) == FALSE) {
                elog(1, "invalid description '%s'", optarg);
                help_usage("prj-set");
                return 1;
            }
            atleast_one_key_set = TRUE;
            ctx->units = tman_unit_add(ctx->units, "desc", optarg);
            break;
        case 'h':
            showhelp = TRUE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("project-set");
    if (atleast_one_key_set == FALSE) {
        elog(1, "gotta supply one of the options");
        help_usage("project-set");
        return 1;
    }

    i = optind;
    do {
        int status;
        args.project = argv[i];

        if ((status = tman_project_set(ctx, &args)) != LIBTMAN_OK) {
            if (quiet == FALSE)
                elog(status, errfmt, argv[i], tman_strerror(status));
        }
    } while (++i < argc);

    ctx->units = tman_unit_free(ctx->units);
    return 0;
}

// roach: maybe it'll be useful
static int _project_show(int argc, char **argv, tman_ctx_t * ctx)
{
    tman_arg_t args;
    int c, i, quiet, showhelp, status;
    struct tman_unit *unitbin, *unitpgn;
    const char *errfmt = "cannot show project units '%s': %s";

    unitbin = unitpgn = NULL;
    quiet = showhelp = FALSE;
    args.project = args.board = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":b:hq")) != -1) {
        switch (c) {
        case 'b':
            args.board = optarg;
            break;
        case 'h':
            showhelp = TRUE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("project-show");

    i = optind;
    do {
        args.project = argv[i];
        if ((status = tman_project_get(ctx, &args)) != LIBTMAN_OK) {
            if (quiet == FALSE)
                elog(status, errfmt, argv[i], tman_strerror(status));
            continue;
        }

        printf("%-7s : %s\n", "project", args.project);
        for (unitbin = ctx->units; unitbin; unitbin = unitbin->next)
            printf("%-7s : %s\n", unitbin->key, unitbin->val);

        // TODO: add plugin output
    } while (++i < argc);

    return status;
}

static int _project_sync(int argc, char **argv, tman_ctx_t * ctx)
{
    tman_arg_t args;
    int c, i, quiet, showhelp, status;
    const char *errfmt = "cannot switch to '%s': %s";

    quiet = showhelp = FALSE;
    args.project = args.board = args.taskid = NULL;
    while ((c = getopt(argc, argv, ":b:hnq")) != -1) {
        switch (c) {
        case 'b':
            args.board = optarg;
            break;
        case 'h':
            showhelp = TRUE;
            break;
        case 'n':
            //opt.prj_switch = FALSE;
            break;
        case 'q':
            quiet = TRUE;
            break;
        case ':':
            return elog(1, "option `-%c' requires an argument", optopt);
        default:
            return elog(1, "invalid option `-%c'", optopt);
        }
    }

    if (showhelp)
        return help_usage("project-sync");

    i = optind;
    do {
        args.project = argv[i];
        if ((status = tman_project_column_set(ctx, &args)) != LIBTMAN_OK) {
            if (quiet == FALSE)
                elog(status, errfmt, argv[i], tman_strerror(status));
        }
    } while (++i < argc);

    //return opt.prj_switch && status == LIBTMAN_OK ? tman_pwd_project() : status;
    return status == LIBTMAN_OK ? tman_pwd_project() : status;
}

static const builtin_t prjcmds[] = {
    {.name = "add",.func = &_project_add},
    {.name = "del",.func = &_project_del},
    {.name = "list",.func = &_project_list},
    {.name = "prev",.func = &_project_prev},
    {.name = "rename",.func = &_project_rename},
    {.name = "set",.func = &_project_set},
    {.name = "show",.func = &_project_show},
    {.name = "sync",.func = &_project_sync},
};

int tman_cli_project(int argc, char **argv, tman_ctx_t * ctx)
{
    char *cmd = argv[1] != NULL ? argv[1] : "list";

    for (int i = 0; i < ARRAY_SIZE(prjcmds); ++i)
        if (strcmp(cmd, prjcmds[i].name) == 0)
            return prjcmds[i].func(argc - 1, argv + 1, ctx);

    return elog(1, "'%s': no such project command", cmd);
}
