local core = require("core.core")
local help = require("aux.help")
local getopt = require("posix.unistd").getopt

---Add a new task.
local function builtin_add()
    local envname, id
    local cmdname = "add"
    local optstr = "d:hp:t:"
    local last_index = 1
    local keyhelp
    local options = {
        prio = "mid",
        desc = "autogenerated task description " .. tostring(os.date("%s")),
    }

    for optopt, optarg, optind in getopt(arg, optstr) do
        if optopt == "?" then
            return core.die(1, "unrecognized option", arg[optind - 1])
        end

        last_index = optind
        if optopt == "d" then
            options.desc = optarg
        elseif optopt == "h" then
            keyhelp = true
        elseif optopt == "p" then
            options.prio = optarg
        end
    end

    if keyhelp then
        help.usage(cmdname)
        return 1
    end

    id = arg[last_index]
    envname = arg[last_index + 1]
    core.id_add(envname, id)

    for k, v in pairs(options) do
        core.id_set(envname, id, k, v)
    end

    return 0
end

return builtin_add
