--- Operate on task unit inside meta data.
-- Metadata like date, description and so on.
-- @module TaskUnit

local utils = require("aux.utils")
local unit = require("aux.unit")
local dirent = require("posix.dirent")
local errmod = require("core.errmod")

local taskunit = {}
local dirpath

---Init module.
---@param unitdir string
---@return boolean
function taskunit.init(unitdir)
    dirpath = unitdir
    return true
end

---Get task unit values.
---@param env string
---@param id string
---@return table
function taskunit.get(env, id)
    unit.init(dirpath .. "/" .. env .. "/" .. id .. "/.tman" .. "/unit")
    return unit.get()
end

---Check if task unit exists.
---@param env string
---@param id string
---@return boolean
function taskunit.ext(env, id)
    return next(taskunit.get(env, id))
end

---Check unit key value.
---@param key string
---@param val string
---@return boolean
function taskunit.chk(key, val)
    -- roachme: gotta make it flexible, not hard-coded
    local prios = { "lowest", "low", "mid", "high", "highest" }

    if key == "id" then
        local rgx = "^[%w]+[-]*[%w]+$"
        return string.match(val, rgx) == val
    elseif key == "desc" then
        local rgx = "^[%w]+[%w-%s]*[%w]*"
        return string.match(val, rgx) == val
    elseif key == "prio" then
        for _, v in pairs(prios) do
            if val == v then
                return true
            end
        end
        return false
    elseif key == "date" then
        return true
    end
    return false
end

---Set task unit values.
---@param env string
---@param id string
---@param key string
---@param val string
---@return boolean
function taskunit.set(env, id, key, val)
    unit.init(dirpath .. "/" .. env .. "/" .. id .. "/.tman" .. "/unit")

    if not taskunit.chk(key, val) then
        return errmod.set(errmod.EIDIL)
    end
    unit.set(key, val)
    return unit.save()
end

---Add a task unit.
---@param env string
---@param id string
---@return boolean
function taskunit.add(env, id)
    local unitdir = dirpath .. "/" .. env .. "/" .. id .. "/.tman"
    local options = {
        id = id,
        prio = "mid",
        desc = "autogenerated descriptioN",
        date = tostring(os.date("%Y%m%d")),
    }

    if taskunit.ext(env, id) then
        return false
    elseif not utils.mkdir(unitdir) then
        return false
    end

    -- set task default values.
    for k, v in pairs(options) do
        taskunit.set(env, id, k, v)
    end
    return true
end

---Delete task unit.
---@param env string
---@param id string
---@return boolean
function taskunit.del(env, id)
    local fpath = dirpath .. "/" .. env .. "/" .. id .. "/unit"
    return utils.rm(fpath) == true
end

---Get list of task ids in environment.
---@param env string
---@return table
function taskunit.list(env)
    local list = {}
    local udirpath = dirpath .. "/" .. env

    for _, id in pairs(dirent.dir(udirpath)) do
        -- eliminate parent and current directories.
        if id ~= "." and id ~= ".." then
            table.insert(list, id)
        end
    end
    return list
end

return taskunit
