--- Operate on task unit inside meta data.
-- Metadata like date, description and so on.
-- @module TaskUnit

local utils = require("aux.utils")
local dirent = require("posix.dirent")
local unitdb = require("aux.unitdb")

local taskunit = {}
local dirpath

---Init module.
---@param unitdir string
---@return boolean
function taskunit.init(unitdir)
    dirpath = unitdir
    return true
end

---Get task units values.
---@param envname string
---@param id string
---@return table
function taskunit.get(envname, id)
    unitdb.init(dirpath .. "/" .. envname .. "/" .. id .. "/unit")
    return unitdb.get()
end

---Check if task unit exists.
---@param envname string
---@param id string
---@return boolean
function taskunit.ext(envname, id)
    return next(taskunit.get(envname, id))
end

---Check unit key value.
---@param key string
---@param val string
---@return boolean
function taskunit.chk(key, val)
    local types = { "bugfix", "feature", "hotfix" }
    local prios = { "lowest", "low", "mid", "high", "highest" }

    if key == "id" then
        local rgx = "^[%w]+[-]*[%w]+$"
        return string.match(val, rgx) == val
    elseif key == "desc" then
        local rgx = "^[%w]+[%w-%s]*[%w]*"
        return string.match(val, rgx) == val
    elseif key == "prio" then
        for _, v in pairs(prios) do
            if val == v then
                return true
            end
        end
        return false
    elseif key == "type" then
        for _, v in pairs(types) do
            if val == v then
                return true
            end
        end
        return false
    end

    io.stderr:write("no such key: ", key, "\n")
    return false
end

---Set task unit values.
---@param envname string
---@param id string
---@param key string
---@param val string
---@return boolean
function taskunit.set(envname, id, key, val)
    unitdb.init(dirpath .. "/" .. envname .. "/" .. id .. "/unit")

    if not taskunit.chk(key, val) then
        io.stderr:write("illegal value ", key, " ", val, "\n")
        return false
    end
    unitdb.set(key, val)
    return unitdb.save()
end

---Add a task unit.
---@param envname string
---@param id string
---@return boolean
function taskunit.add(envname, id)
    local options = {
        id = id,
        type = "bugfix",
        prio = "mid",
        desc = "autogenerated description",
    }

    if taskunit.ext(envname, id) then
        io.stderr:write("task id already exists\n")
        return false
    end

    for k, v in pairs(options) do
        taskunit.set(envname, id, k, v)
    end
    return true
end

---Delete task unit.
---@param envname string
---@param id string
---@return boolean
function taskunit.del(envname, id)
    local fpath = dirpath .. "/" .. envname .. "/" .. id .. "/unit"
    return utils.rm(fpath) == true
end

---Get list of task ids in environment.
---@param envname string
---@return table
function taskunit.list(envname)
    local list = {}
    local udirpath = dirpath .. "/" .. envname

    for _, id in pairs(dirent.dir(udirpath)) do
        if id ~= "." and id ~= ".." then
            table.insert(list, id)
        end
    end
    return list
end

return taskunit
