--- Operate on task unit inside meta data.
-- Metadata like date, description and so on.
-- @module TaskUnit

local utils = require("aux.utils")
local dirent = require("posix.dirent")
local unitdb = require("core.aux.unitdb")
local errmod = require("core.errmod")

local taskunit = {}
local dirpath

local status = {
    CURR = 1,
    PREV = 2,
    ACTV = 3,
    COMP = 4,
    ARCH = 5,
}

---Init module.
---@param unitdir string
---@return boolean
function taskunit.init(unitdir)
    dirpath = unitdir
    return true
end

---Get task unit values.
---@param env string
---@param id string
---@return table
function taskunit.get(env, id)
    unitdb.init(dirpath .. "/" .. env .. "/" .. id .. "/.tman" .. "/unit")
    return unitdb.get()
end

---Check if task unit exists.
---@param env string
---@param id string
---@return boolean
function taskunit.ext(env, id)
    return next(taskunit.get(env, id))
end

---Check unit key value.
---@param key string
---@param val string
---@return boolean
function taskunit.chk(key, val)
    local types = { "bugfix", "feature", "hotfix" }
    local prios = { "lowest", "low", "mid", "high", "highest" }

    if key == "id" then
        local rgx = "^[%w]+[-]*[%w]+$"
        return string.match(val, rgx) == val
    elseif key == "desc" then
        local rgx = "^[%w]+[%w-%s]*[%w]*"
        return string.match(val, rgx) == val
    elseif key == "prio" then
        for _, v in pairs(prios) do
            if val == v then
                return true
            end
        end
        return false
    elseif key == "type" then
        for _, v in pairs(types) do
            if val == v then
                return true
            end
        end
        return false
    elseif key == "date" then
        return true
    end
    return false
end

---Set task unit values.
---@param env string
---@param id string
---@param key string
---@param val string
---@return boolean
function taskunit.set(env, id, key, val)
    unitdb.init(dirpath .. "/" .. env .. "/" .. id .. "/.tman" .. "/unit")

    if not taskunit.chk(key, val) then
        return errmod.set(errmod.EIDIL)
    end
    unitdb.set(key, val)
    return unitdb.save()
end

---Add a task unit.
---@param env string
---@param id string
---@return boolean
function taskunit.add(env, id)
    local options = {
        id = id,
        type = "bugfix",
        prio = "mid",
        desc = "autogenerated descriptioN",
        date = tostring(os.date("%Y%m%d")),
    }

    if taskunit.ext(env, id) then
        return false
    elseif not utils.mkdir(dirpath .. "/" .. env .. "/" .. id .. "/.tman") then
        return false
    end

    -- set task default values.
    for k, v in pairs(options) do
        taskunit.set(env, id, k, v)
    end
    return true
end

---Delete task unit.
---@param env string
---@param id string
---@return boolean
function taskunit.del(env, id)
    local fpath = dirpath .. "/" .. env .. "/" .. id .. "/unit"
    return utils.rm(fpath) == true
end

---Get list of task ids in environment.
---@param env string
---@return table
function taskunit.list(env)
    local list = {}
    local udirpath = dirpath .. "/" .. env

    for _, id in pairs(dirent.dir(udirpath)) do
        if id ~= "." and id ~= ".." then
            if utils.access(udirpath .. "/" .. id) then
                table.insert(list, id)
            end
        end
    end
    return list
end

return taskunit
