#!/usr/bin/env bash

set -e

PROGRAM="teccli"

DIR_TECCONF="$HOME/.config/tec"
DIR_PLUGIN="$HOME/.local/lib/tec"
DIR_BIN="$HOME/.local/bin"
FILE_CONFIG="$DIR_TECCONF/tec.cfg"

mkdir -p "$DIR_TECCONF"
mkdir -p "$DIR_BIN"
mkdir -p "$DIR_PLUGIN"


cp templates/tec.cfg "$FILE_CONFIG"
rm -rf "$DIR_PLUGIN" && cp -r pgn "$DIR_PLUGIN"

cp "$PROGRAM" "$DIR_BIN"
echo "NOTE: Make sure '$DIR_BIN' is in your environment variable '$$PATH'"

# TODO: Install plugin default configs too
bash pgn/install.sh

