--- Provide help on commands and general usage.
-- @module help

local function show_usage()
    io.stdout:write(([[
Usage: %s COMMAND [OPTION] [ID] [ENV]

List of available commands:

System:
  arch    - backup and/or restore
  init    - init directory structure

Basic:
  add     - add a new task
  del     - delete a task
  env     - manipulate environments
  prev    - switch to previous task
  set     - set task unit values
  sync    - synchronize task (under development)
  use     - switch to specific task

Additional:
  cfg     - config workflow
  pgn     - manipulate plugins: struct, git, make, time

Info:
  cat     - cat task info
  help    - display help information
  list    - list task environment
  ver     - show version

'%s help COMMAND' to get detailed info about command.
'%s help %s' to get info about util itself.
]]):format(progname, progname, progname, progname))
end

local cmds = {
    {
        name = progname,
        desc = [[
tman - Terminal task manager.

Util to switch between tasks, git branches and make the workflow easy and
less confusing. You no longer need to memerize task ids, branche names,
cd between directories, lose task notes, but instead look
for 'em in nice structured way.
]],
    },
    {
        name = "init",
        desc = [[
Usage: tman init
Initialize directory structure.
]],
    },
    {
        name = "archive",
        desc = [[
Usage: tman archive OPTION
Make backup and restore util data.

Options:
    -R          include repos into archive (default: false)
    -b FILE     create backup (default extension: .tar)
    -h          Show this help message.
    -r FILE     restore from archive
]],
    },
    {
        name = "cfg",
        desc = [[
Usage: tman cfg OPTION
Work with config files.

Options:
    -b      - set base path. Prefix is user home.
    -i      - set install path
              questionable, cuz util gotta change path in .shellrc
    -s      - show config: system & user
]],
    },
    {
        name = "add",
        desc = [[
Usage: tman add [OPTION] ID
Add new task.

Options:
    -d      task description (default: autogenerated message)
    -h      show this help message.
    -p      task priority. Values: [highest|high|mid|low|lowest]
    -t      task type. Values: [bugfix|hotfix|feature]
]],
    },
    {
        name = "del",
        desc = [[
Usage: tman del [ID]
Delete task.
ID - default is current task.
]],
    },
    {
        name = "set",
        desc = [[
Usage: tman set OPTION [ID]
Amend task items.
ID - default is current task.

Options:
    -i      set task id
    -d      set task description
    -l      set task link
    -p      set task priority. Values: [highest|high|mid|low|lowest]
    -t      set task type. Values: [bugfix|hotfix|feature]
]],
    },
    {
        name = "use",
        desc = [[
Usage: tman use ID
Switch to specified task. Use `tman list` to see existing tasks.

Notes:
    ID - taks ID. Default is current task.
]],
    },
    {
        name = "env",
        desc = [[
Usage: tman env COMMAND [ENVNAME]
Define or display environments.

ENVNAME - environment name

COMMANDs:
    add     - add new environment
    curr    - show current environment
    del     - delete an environment
    list    - list environments
    prev    - switch to previous environment
    use     - use environment
]],
    },
    {
        name = "prev",
        desc = [[
Usage: tman prev [ENVNAME]
Switch to previous task if set.

ENVNAME - environment name. Under development (pro'ly).

Options:
    -h   Show this help message.
]],
    },
    {
        name = "list",
        desc = [[
Usage: tman list [OPTION] [ENVNAME]
List task ids with description.

Options:
    -c   List only complete tasks.
    -a   List only active tasks (default).
    -A   List all tasks: active and complete.
    -h   Show this help message.

Notes:
    *   Marks current task.
    -   Makrs previous task.
]],
    },
    {
        name = "cat",
        desc = [[
Usage: tman cat [OPTION] [ID]
Show task units.
ID - task id (default is current task).

Options:
    -k   cat specific task unit
    -h   Show this help message.
]],
    },
    {
        name = "help",
        desc = [[
Usage: tman help [COMMAND]
Show help message. If `COMMAND' applied then show info about command.
]],
    },
    {
        name = "ver",
        desc = [[
Usage: tman ver
Show tman version.
]],
    },
}

---Get info about command.
---@param cmdname string
---@return number
local function help_usage(cmdname)
    local errmsg = "%s: no such command '%s'. Use '%s help' for more info.\n"

    if not cmdname then
        show_usage()
        return 0
    end

    for _, cmd in ipairs(cmds) do
        if cmd.name == cmdname then
            io.stdout:write(cmd.desc)
            return 0
        end
    end

    io.stderr:write(errmsg:format(progname, cmdname, progname))
    return 1
end

return {
    usage = help_usage,
}
