--- Provide help on commands and general usage.help
-- @module help

local function show_usage()
    io.stdout:write(([[
Usage: %s COMMAND [OPTION] [ID] [ENV]

List of available commands:

System:
  arch    - backup and/or restore
  cfg     - manipulate system configuration
  fix     - fix system database
  init    - init directory structure

Manipulation:
  add     - add a new task
  del     - delete a task
  move    - move task to another environment
  prev    - switch to previous task
  set     - set task unit values
  use     - switch to specific task

Additional:
  clean   - delete finished tasks
  env     - manipulate environments
  sync    - synchronize task (under development)
  pgn     - plugin manager

Info:
  cat     - cat task info
  help    - display help information
  list    - list task environment
  ver     - show version

'%s help COMMAND' to get detailed info about command.
'%s help %s' to get info about util itself.
]]):format(progname, progname, progname, progname))
end

local cmds = {
    {
        name = progname,
        desc = [[
tman - Terminal task manager.

Util to switch between tasks, git branches and make the workflow easy and
less confusing. You no longer need to memerize task ids, branche names,
cd between directories, lose task notes, but instead look
for 'em in nice structured way.
]],
    },
    {
        name = "init",
        desc = [[
Usage: tman init
Initialize directory structure.
]],
    },
    {
        name = "archive",
        desc = [[
Usage: tman archive OPTION
Make backup and restore util data.

Options:
    -R          include repos into archive (default: false)
    -b FILE     create backup (default extension: .tar)
    -h          Show this help message.
    -r FILE     restore from archive
]],
    },
    {
        name = "cfg",
        desc = [[
Usage: tman cfg OPTION
Work with config files.

Options:
    -b      - set base path. Prefix is user home.
    -i      - set install path
              questionable, cuz util gotta change path in .shellrc
    -s      - show config: system & user
]],
    },
    {
        name = "add",
        desc = [[
Usage: tman add [OPTION]... ID [ENVNAME]
Add new task.

Options:
    -d      task description. Default: autogenerated message
    -h      show this help message.
    -p      task priority. Default: mid
    -t      task type. Default: bugfix

Task priorities: [ highest | high | mid | low | lowest ]
Task types:      [ bugfix | feature | hotfix ]
ENVNAME: environment to add a new task to. Default is current environment.
]],
    },
    {
        name = "del",
        desc = [[
Usage: tman del [ID] [ENVNAME]
Delete task.
ID - default is current task.
]],
    },
    {
        name = "set",
        desc = [[
Usage: tman set OPTION... [ID] [ENVNAME]
Amend task items.
ID - default is current task.

Options:
    -i      set task id
    -d      set task description
    -p      set task priority. Values: [highest|high|mid|low|lowest]
    -t      set task type. Values: [bugfix|hotfix|feature]

Values:
ENVNAME     Environment to add a new task to. If does not exist then
            will be created. Default is current environment.
ID          Task id to set values to. Default: current task.
]],
    },
    {
        name = "use",
        desc = [[
Usage: tman use ID [ENVNAME]
Switch to specified task. Use `tman list` to see existing tasks.

Notes:
    ID      - taks ID. Default is current task.
    ENVNAME - environment name. Default is current environment.
]],
    },
    {
        name = "env",
        desc = [[
Usage: tman env COMMAND [ENVNAME]
Define or display environments.

ENVNAME - environment name

COMMANDs:
    add     - add new environment
    del     - delete an environment
    list    - list environments
    prev    - switch to previous environment
    use     - use environment
]],
    },
    {
        name = "prev",
        desc = [[
Usage: tman prev [ENVNAME]
Switch to previous task if set.

ENVNAME - environment name. Under development (pro'ly).

Options:
    -h   Show this help message.
]],
    },
    {
        name = "list",
        desc = [[
Usage: tman list [OPTION] [ENVNAME]
List task ids with description.

Options:
    -c   List only complete tasks.
    -a   List only active tasks (default).
    -A   List all tasks: active and complete.
    -h   Show this help message.

Notes:
    *   Current task.
    ^   Previous task.
    +   Active task.
    -   Completed task.
]],
    },
    {
        name = "sync",
        desc = [[
Usage: tman sync [OPTION]
Synchronize with task.
]],
    },
    {
        name = "cat",
        desc = [[
Usage: tman cat [OPTION] [ID] [ENVNAME]
Show task units.
ID - task id (default is current task).

Options:
    -k   cat specific task unit
    -h   Show this help message.
]],
    },
    {
        name = "help",
        desc = [[
Usage: tman help [COMMAND]
Show help message. If `COMMAND' applied then show info about command.
]],
    },
    {
        name = "ver",
        desc = [[
Usage: tman ver
Show tman version.
]],
    },
}

---Get info about command.
---@param cmdname string
---@return number
local function help_usage(cmdname)
    local errmsg = "%s: no such command '%s'. Use '%s help' for more info.\n"

    if not cmdname then
        show_usage()
        return 0
    end

    for _, cmd in ipairs(cmds) do
        if cmd.name == cmdname then
            io.stdout:write(cmd.desc)
            return 0
        end
    end

    io.stderr:write(errmsg:format(progname, cmdname, progname))
    return 1
end

return {
    usage = help_usage,
}
